services:
  - type: static_site
    name: engleap
    rootDir: srs-app
    buildCommand: npm ci --include=optional && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
